apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-project777.fullname" . }}
  labels:
    {{- include "devops-project777.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "devops-project777.selectorLabels" . | nindent 4 }}
